/* Copyright (c) 2025 JC Technolabs

   Permission is hereby granted, free of charge, to any person
   obtaining a copy of this software and associated documentation files
   (the "Software"), to deal in the Software without restriction,
   including without limitation the rights to use, copy, modify, merge,
   publish, distribute, sublicense, and/or sell copies of the Software,
   and to permit persons to whom the Software is furnished to do so,
   subject to the following conditions:

   The above copyright notice and this permission notice shall be
   included in all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
   OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
   SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.*/

#include <fstream>
#include <chrono>
#include <iomanip>

#include "engine.h"
#include "session/fileWriter.h"

namespace fs = std::filesystem;

namespace AIAssistant
{
    FileWriter& FileWriter::Get()
    {
        static FileWriter instance;
        return instance;
    }

    void FileWriter::Write(fs::path const& filePath, std::string const& content)
    {
        std::lock_guard<std::mutex> guard(m_Mutex);

        try
        {
            fs::create_directories(filePath.parent_path());
            std::ofstream out(filePath, std::ios::out | std::ios::trunc);

            if (!out)
            {
                LOG_APP_ERROR("FileWriter: Could not open file for writing: {}", filePath.string());
                return;
            }

            out << content;
            LOG_APP_INFO("FileWriter: Wrote file '{}'", filePath.string());
        }
        catch (const std::exception& e)
        {
            LOG_APP_ERROR("FileWriter: Exception writing file '{}': {}", filePath.string(), e.what());
        }
    }

    void FileWriter::WriteWithHeader(fs::path const& filePath, std::string const& content, std::string const& model,
                                     bool appendTimestamp)
    {
        std::lock_guard<std::mutex> guard(m_Mutex);

        try
        {
            fs::create_directories(filePath.parent_path());
            std::ofstream out(filePath, std::ios::out | std::ios::trunc);

            if (!out)
            {
                LOG_APP_ERROR("FileWriter: Could not open file for writing: {}", filePath.string());
                return;
            }

            out << "# Generated by JarvisAgent\n";
            out << "# Model: " << model << "\n";

            if (appendTimestamp)
            {
                auto now = std::chrono::system_clock::now();
                auto time = std::chrono::system_clock::to_time_t(now);
                out << "# Timestamp: " << std::put_time(std::localtime(&time), "%Y-%m-%d %H:%M:%S") << "\n";
            }

            out << "\n" << content;
            LOG_APP_INFO("FileWriter: Wrote output file with header: {}", filePath.string());
        }
        catch (const std::exception& e)
        {
            LOG_APP_ERROR("FileWriter: Exception writing file '{}': {}", filePath.string(), e.what());
        }
    }
} // namespace AIAssistant
