#!/bin/bash
set -e

if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then
    echo "==> Removing Python virtual environment ..."
    rm -rf /opt/jarvisagent/.venv

    echo "==> You may want to remove /opt/jarvisagent/ manually if custom data remains."
fi
