#!/usr/bin/env python3
"""
Combine per-class Markdown docs (generated by JarvisAgent AI tasks) into a single navigable document.

Expected usage (via JCWF python task):
- Input: docsDirectory -> points at the workflow's queue root, e.g. ../queue/jarvisCppDocu
- Output: combinedDocumentation.md in the task working directory

The script is intentionally robust:
- It scans recursively for docu.output.md (preferred) or docu.md.
- It derives a "source path" from the task folder name (doc_application_..._h => application/.../*.h).
- It builds a folder-structured Table of Contents with links.
- It avoids work if the combined doc is newer than all inputs.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def _safe_read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")


def _derive_source_header_path_from_task_folder(task_folder_name: str) -> str:
    """
    folder name: doc_application_file_fileWatcher_h
    -> application/file/fileWatcher.h
    """
    prefix = "doc_"
    suffix = "_h"

    if not task_folder_name.startswith(prefix) or not task_folder_name.endswith(suffix):
        return task_folder_name

    core = task_folder_name[len(prefix) : -len(suffix)]
    # core uses underscores as separators between path components.
    parts = core.split("_")
    return "/".join(parts) + ".h"


def _collect_docs(queue_root: Path) -> List[Tuple[str, Path]]:
    """
    Returns list of (sourceHeaderPath, docPath).
    Prefers docu.output.md if present in a task folder; falls back to docu.md.
    """
    docs: List[Tuple[str, Path]] = []

    if not queue_root.exists():
        return docs

    for child in sorted(queue_root.iterdir()):
        if not child.is_dir():
            continue

        doc_output = child / "docu.output.md"
        doc_plain = child / "docu.md"

        doc_path: Optional[Path] = None
        if doc_output.is_file():
            doc_path = doc_output
        elif doc_plain.is_file():
            doc_path = doc_plain

        if doc_path is None:
            continue

        source_path = _derive_source_header_path_from_task_folder(child.name)
        docs.append((source_path, doc_path))

    return docs


def _latest_mtime(paths: List[Path]) -> float:
    latest = 0.0
    for path in paths:
        try:
            latest = max(latest, path.stat().st_mtime)
        except OSError:
            continue
    return latest


def _anchor_id(text: str) -> str:
    # GitHub-style-ish anchor: lowercase, spaces -> -, strip non-alnum/-.
    out_chars: List[str] = []
    for ch in text.strip().lower():
        if ch.isalnum():
            out_chars.append(ch)
        elif ch in [" ", "-", "_", "/"]:
            out_chars.append("-")
        # ignore everything else
    anchor = "".join(out_chars)
    while "--" in anchor:
        anchor = anchor.replace("--", "-")
    return anchor.strip("-")


def BuildCombinedDocumentation(docsDirectory: str, context: Optional[dict] = None) -> Dict[str, str]:
    """
    JCWF entry point.

    Args:
        docsDirectory: directory that contains per-task folders (e.g. ../queue/jarvisCppDocu).
        context: optional runtime context dict (JarvisAgent provides this when the task declares an input named 'context').

    Returns:
        A dict (optional outputs); not required by JarvisAgent but allowed.
    """
    context = context or {}

    task_working_directory = Path(context.get("_task_working_directory", "."))
    workflow_base_directory = Path(context.get("_workflow_base_directory", "."))

    # Resolve docsDirectory robustly.
    docs_root_candidates = [
        Path(docsDirectory),
        task_working_directory / docsDirectory,
        workflow_base_directory / docsDirectory,
        Path.cwd() / docsDirectory,
    ]

    docs_root: Optional[Path] = None
    for candidate in docs_root_candidates:
        candidate = candidate.expanduser()
        try:
            candidate = candidate.resolve()
        except OSError:
            candidate = candidate.absolute()
        if candidate.exists():
            docs_root = candidate
            break

    if docs_root is None:
        raise RuntimeError(f"combine docs: docsDirectory not found: {docsDirectory}")

    docs = _collect_docs(docs_root)
    if not docs:
        raise RuntimeError(f"combine docs: no docu.md or docu.output.md found under: {docs_root}")

    output_path = task_working_directory / "combinedDocumentation.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    newest_input_mtime = _latest_mtime([p for _, p in docs])
    try:
        if output_path.is_file() and output_path.stat().st_mtime >= newest_input_mtime:
            # Up-to-date; no work needed.
            return {"combined_path": str(output_path)}
    except OSError:
        pass

    # Build a folder-structured TOC.
    # Group by folder path: application/file, engine/event, ...
    grouped: Dict[str, List[Tuple[str, Path]]] = {}
    for source_path, doc_path in docs:
        folder = str(Path(source_path).parent).replace("\\", "/")
        grouped.setdefault(folder, []).append((source_path, doc_path))

    lines: List[str] = []
    lines.append("# JarvisAgent C++ Documentation\n")
    lines.append("This document is generated by the **jarvisCppDocu** workflow.\n")
    lines.append("## Table of contents\n")

    # Render folders in a stable order.
    for folder in sorted(grouped.keys()):
        folder_display = folder if folder != "." else "(root)"
        folder_anchor = _anchor_id(f"folder-{folder_display}")
        lines.append(f"- [{folder_display}](#{folder_anchor})")

        for source_path, doc_path in sorted(grouped[folder], key=lambda x: x[0]):
            title = source_path
            anchor = _anchor_id(title)
            lines.append(f"  - [{title}](#{anchor})")

    lines.append("\n---\n")

    # Content section per folder, then per class doc.
    # Provide a relative link to the original per-class markdown for quick jumping.
    for folder in sorted(grouped.keys()):
        folder_display = folder if folder != "." else "(root)"
        folder_anchor = _anchor_id(f"folder-{folder_display}")
        lines.append(f"## {folder_display}\n")
        # explicit HTML anchor for reliability across markdown renderers
        lines.append(f'<a id="{folder_anchor}"></a>\n')

        for source_path, doc_path in sorted(grouped[folder], key=lambda x: x[0]):
            anchor = _anchor_id(source_path)

            try:
                rel_link = os.path.relpath(doc_path, start=output_path.parent)
            except ValueError:
                rel_link = str(doc_path)

            lines.append(f"### {source_path}\n")
            lines.append(f'<a id="{anchor}"></a>\n')
            lines.append(f"*Source doc:* `{rel_link}`\n")
            lines.append("\n")
            lines.append(_safe_read_text(doc_path).rstrip())
            lines.append("\n\n---\n")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return {"combined_path": str(output_path)}
