#!/usr/bin/env python3
"""
Combine per-class Markdown docs (generated by JarvisAgent AI tasks) into a single navigable document.

Expected usage (via JCWF python task):
- Input: docsDirectory -> points at the workflow's queue root, e.g. ../queue/jarvisCppDocu
- Output: combinedDocumentation.md in the task working directory

The script is intentionally robust:
- It scans recursively for docu.output.md (preferred) or docu.md.
- It derives a "source path" from the task folder name (doc_application_..._h => application/.../*.h).
- It builds a folder-structured Table of Contents with links.
- It avoids work if the combined doc is newer than all inputs.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, List, Optional, Tuple


def _safe_read_text(path: Path) -> str:
    try:
        return _strip_outer_markdown_code_fence(path.read_text(encoding="utf-8"))
    except UnicodeDecodeError:
        return _strip_outer_markdown_code_fence(path.read_text(encoding="utf-8", errors="replace"))




def _strip_outer_markdown_code_fence(text: str) -> str:
    """
    Some AI outputs wrap the entire document in a fenced code block like:
        ```markdown
        ...markdown...
        ```
    When this combined doc is rendered, the markdown stays literal.
    This helper removes a single outer fence if present.
    """
    lines = text.splitlines()

    # Find first non-empty line
    start_index = 0
    while start_index < len(lines) and not lines[start_index].strip():
        start_index += 1

    if start_index >= len(lines):
        return text

    first = lines[start_index].strip().lower()
    if not first.startswith("```"):
        return text

    # Accept common fence starters
    if first not in ("```", "```markdown", "```md"):
        # Still treat any ```<lang> as a wrapper if the closing fence exists
        pass

    # Find last non-empty line
    end_index = len(lines) - 1
    while end_index >= 0 and not lines[end_index].strip():
        end_index -= 1

    if end_index <= start_index:
        return text

    last = lines[end_index].strip()
    if last != "```":
        return text

    # Strip exactly one outer wrapper
    stripped_lines = lines[:start_index] + lines[start_index + 1 : end_index] + lines[end_index + 1 :]
    return "\n".join(stripped_lines)
def _derive_source_header_path_from_task_folder(task_folder_name: str) -> str:
    """
    folder name: doc_application_file_fileWatcher_h
    -> application/file/fileWatcher.h
    """
    prefix = "doc_"
    suffix = "_h"

    if not task_folder_name.startswith(prefix) or not task_folder_name.endswith(suffix):
        return task_folder_name

    core = task_folder_name[len(prefix) : -len(suffix)]
    # core uses underscores as separators between path components.
    parts = core.split("_")
    return "/".join(parts) + ".h"


def _collect_docs(queue_root: Path) -> List[Tuple[str, Path]]:
    """
    Returns list of (sourceHeaderPath, docPath).
    Prefers docu.output.md if present in a task folder; falls back to docu.md.
    """
    docs: List[Tuple[str, Path]] = []

    if not queue_root.exists():
        return docs

    for child in sorted(queue_root.iterdir()):
        if not child.is_dir():
            continue

        doc_output = child / "docu.output.md"
        doc_plain = child / "docu.md"

        doc_path: Optional[Path] = None
        if doc_output.is_file():
            doc_path = doc_output
        elif doc_plain.is_file():
            doc_path = doc_plain

        if doc_path is None:
            continue

        source_path = _derive_source_header_path_from_task_folder(child.name)
        docs.append((source_path, doc_path))

    return docs


def _latest_mtime(paths: List[Path]) -> float:
    latest = 0.0
    for path in paths:
        try:
            latest = max(latest, path.stat().st_mtime)
        except OSError:
            continue
    return latest


def _anchor_id(text: str) -> str:
    # GitHub-style-ish anchor: lowercase, spaces -> -, strip non-alnum/-.
    out_chars: List[str] = []
    for ch in text.strip().lower():
        if ch.isalnum():
            out_chars.append(ch)
        elif ch in [" ", "-", "_", "/"]:
            out_chars.append("-")
        # ignore everything else
    anchor = "".join(out_chars)
    while "--" in anchor:
        anchor = anchor.replace("--", "-")
    return anchor.strip("-")



def _auto_find_docs_root(start_dir: Path) -> Path:
    """
    Best-effort fallback when docsDirectory is not provided by JCWF.
    We try to locate a queue root by walking up a few parents and looking for a
    'queue' directory (either as a child or as a sibling via ../queue).
    Then we choose the workflow subdirectory that contains the most per-task doc files.
    """
    search_roots = [start_dir] + list(start_dir.parents)[:8]

    best_candidate: Optional[Path] = None
    best_score = 0

    for root in search_roots:
        candidate_queue_dirs = [
            root / "queue",
            root / ".." / "queue",
        ]
        for queue_dir in candidate_queue_dirs:
            try:
                q = queue_dir.resolve()
            except OSError:
                q = queue_dir.absolute()
            if not q.is_dir():
                continue

            # Choose the workflow folder under queue/ that contains the most task docs.
            for workflow_dir in sorted(q.iterdir()):
                if not workflow_dir.is_dir():
                    continue

                score = 0
                try:
                    for task_dir in workflow_dir.iterdir():
                        if not task_dir.is_dir():
                            continue
                        if (task_dir / "docu.output.md").is_file() or (task_dir / "docu.md").is_file():
                            score += 1
                except OSError:
                    continue

                if score > best_score:
                    best_score = score
                    best_candidate = workflow_dir

    if best_candidate is None or best_score == 0:
        raise RuntimeError(
            "combine docs: docsDirectory was not provided and no suitable ../queue/<workflowId> "
            "folder containing docu.output.md/docu.md could be auto-detected."
        )

    return best_candidate


def BuildCombinedDocumentation(docsDirectory: str = "", context: Optional[dict] = None, **kwargs) -> Dict[str, str]:
    """
    JCWF entry point.

    Args:
        docsDirectory: directory that contains per-task folders (e.g. ../queue/jarvisCppDocu).
        context: optional runtime context dict (JarvisAgent provides this when the task declares an input named 'context').

    Returns:
        A dict (optional outputs); not required by JarvisAgent but allowed.
    """
    context = context or {}


    # Accept alternate input naming from JCWF/dataflow and tolerate missing docsDirectory.
    if not docsDirectory:
        docsDirectory = str(kwargs.get("docsDirectory", "") or kwargs.get("docs_directory", "") or kwargs.get("docsDir", ""))


    task_working_directory = Path(context.get("_task_working_directory", "."))
    workflow_base_directory = Path(context.get("_workflow_base_directory", "."))

    # Resolve docsDirectory robustly.
    # Preferred: docsDirectory passed from JCWF (e.g. ../queue/jarvisCppDocu).
    # Fallback: auto-detect a suitable ../queue/<workflowId> folder based on the current working directory.
    docs_root: Optional[Path] = None

    if docsDirectory:
        docs_root_candidates = [
            Path(docsDirectory),
            task_working_directory / docsDirectory,
            workflow_base_directory / docsDirectory,
            Path.cwd() / docsDirectory,
        ]

        for candidate in docs_root_candidates:
            candidate = candidate.expanduser()
            try:
                candidate = candidate.resolve()
            except OSError:
                candidate = candidate.absolute()
            if candidate.exists():
                docs_root = candidate
                break
    else:
        docs_root = _auto_find_docs_root(Path.cwd())

    if docs_root is None:
        raise RuntimeError(f"combine docs: docsDirectory not found: {docsDirectory}")

    docs = _collect_docs(docs_root)
    if not docs:
        raise RuntimeError(f"combine docs: no docu.md or docu.output.md found under: {docs_root}")

    output_path = task_working_directory / "combinedDocumentation.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    newest_input_mtime = _latest_mtime([p for _, p in docs])
    try:
        if output_path.is_file() and output_path.stat().st_mtime >= newest_input_mtime:
            # Up-to-date; no work needed.
            return {"combined_path": str(output_path)}
    except OSError:
        pass

    # Build a folder-structured TOC.
    # Group by folder path: application/file, engine/event, ...
    grouped: Dict[str, List[Tuple[str, Path]]] = {}
    for source_path, doc_path in docs:
        folder = str(Path(source_path).parent).replace("\\", "/")
        grouped.setdefault(folder, []).append((source_path, doc_path))

    lines: List[str] = []
    lines.append("# JarvisAgent C++ Documentation\n")
    lines.append("This document is generated by the **jarvisCppDocu** workflow.\n")
    lines.append("## Table of contents\n")

    # Render folders in a stable order.
    for folder in sorted(grouped.keys()):
        folder_display = folder if folder != "." else "(root)"
        folder_anchor = _anchor_id(f"folder-{folder_display}")
        lines.append(f"- [{folder_display}](#{folder_anchor})")

        for source_path, doc_path in sorted(grouped[folder], key=lambda x: x[0]):
            title = source_path
            anchor = _anchor_id(title)
            lines.append(f"  - [{title}](#{anchor})")

    lines.append("\n---\n")

    # Content section per folder, then per class doc.
    # Provide a relative link to the original per-class markdown for quick jumping.
    for folder in sorted(grouped.keys()):
        folder_display = folder if folder != "." else "(root)"
        folder_anchor = _anchor_id(f"folder-{folder_display}")
        lines.append(f"## {folder_display}\n")
        # explicit HTML anchor for reliability across markdown renderers
        lines.append(f'<a id="{folder_anchor}"></a>\n')

        for source_path, doc_path in sorted(grouped[folder], key=lambda x: x[0]):
            anchor = _anchor_id(source_path)

            try:
                rel_link = os.path.relpath(doc_path, start=output_path.parent)
            except ValueError:
                rel_link = str(doc_path)

            lines.append(f"### {source_path}\n")
            lines.append(f'<a id="{anchor}"></a>\n')
            lines.append(f"*Source doc:* `{rel_link}`\n")
            lines.append("\n")
            lines.append(_safe_read_text(doc_path).rstrip())
            lines.append("\n\n---\n")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return {"combined_path": str(output_path)}